[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_version = "20"
  external_node_modules = ["firebase"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
